Repository JuliaMolSim/DFTK.jl, pull requests merged in 2019-08, with the labels that each got.

#13 Brillouin zone symmetry for density computation
  .travis.yml
  Manifest.toml
  deps/build.jl
  examples/silicon_free_electron.jl
  examples/silicon_lda.jl
  src/DFTK.jl
  src/core/PlaneWaveBasis.jl
  src/core/PotXc.jl
  src/core/compute_density.jl
  src/core/lobpcg.jl
  src/core/lobpcg_scipy.jl
  src/core/scf_damped.jl
  src/core/scf_nlsolve.jl
  src/core/xc_evaluate.jl
  src/utils/bzmesh.jl
  src/utils/spglib.jl
  test/PlaneWaveBasis.jl
  test/build_local_potential.jl
  test/build_nonlocal_projectors.jl
  test/bzmesh.jl
  test/compute_density.jl
  test/energies_guess_density.jl
  test/energy_ewald.jl
  test/expensive/lobpcg.jl
  test/expensive/silicon_lda.jl
  test/expensive/silicon_noXC.jl
  test/fourier_transforms.jl
  test/lobpcg.jl
  test/runtests.jl
  test/scf_compare.jl
  test/silicon_runners.jl
  test/silicon_testcases.jl
Labels: feature

#17 Doc and cleanup
  README.md
  codegen/xc_fallback/README.md
  deps/build.jl
  src/core/energy_ewald.jl
  src/utils/guess_gaussian_sad.jl
Labels: documentation

#8 Support smearing
  Manifest.toml
  Project.toml
  src/core/occupation.jl
  src/utils/self_consistent_field.jl
  test/occupation.jl
  test/runtests.jl
Labels: feature

#18 [WIP] Switch lobpcg to the one from antoine-levitt/LOBPCG
  examples/silicon_lda.jl
  src/core/lobpcg.jl
  src/core/lobpcg_hyper.jl
  src/core/lobpcg_hyper_impl.jl
  src/core/lobpcg_qr.jl
  src/core/lobpcg_scipy.jl
  src/core/scf_damped.jl
  src/core/scf_nlsolve.jl
  test/lobpcg.jl
Labels: performance

#14 Refactor SCF
  Manifest.toml
  src/DFTK.jl
  src/core/lobpcg.jl
  src/core/lobpcg_hyper.jl
  src/core/lobpcg_hyper_impl.jl
  src/core/scf.jl
  src/core/scf_damped.jl
  src/core/scf_nlsolve.jl
  src/core/scf_solvers.jl
  src/utils/self_consistent_field.jl
  test/scf_compare.jl
  test/silicon_lda.jl
Labels: feature
